version: "3.7"
services: 
  database_vibefound:
    image: postgres
    container_name: database_findpackage
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=findpackage
      - POSTGRES_DB=findpackage
    volumes: 
      - pgdata:/data/postgres
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

#  app:
#    build: .
#    container_name: vibefound
#    ports: 
#      - 3333:3333
#    volumes: 
#      - .:/usr/app
#    links:
#      - database_vibefound
#    depends_on: 
#      - database_vibefound

volumes:
  pgdata:
    driver: local
   
   
   
   
   
   
   
  

 

   