import { Router } from "express";
import multer from "multer";
import { CreatePathController } from "../../../../modules/steps/useCases/createPath/CreatePathController";
import { GetPathsByRouteIdController } from "../../../../modules/steps/useCases/getPathsByRouteId/GetPathsByRouteIdController";
import { ensureAuthenticated } from "../middlewares/ensureAuthenticated";
import { ensureEnterprise } from "../middlewares/ensureEnterprise";
const pathsRoutes = Router();
const createPathController = new CreatePathController();
const getPathsByRouteIdController = new GetPathsByRouteIdController();
pathsRoutes.post("/",ensureAuthenticated,ensureEnterprise,createPathController.handle);
pathsRoutes.get("/byRoute/:route_id",getPathsByRouteIdController.handle);
export { pathsRoutes };